### ISSUE TITLE
Java Jar can be downloaded on Windows machines

### ISSUE THREAD

**Issue by ahtrotta** [getappmap/appmap-intellij-plugin#316]
When I ran the latest release candidate (`0.40.0`) on Windows I was unable to use the plugin because the Java agent Jar file was not downloaded. Here's the error in the log file:

```
2023-06-27 13:59:00,680 [  89123]   WARN - #appland.javaAgent.AppMapJavaAgentDownloadService - error creating AppMap agent directory: C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.1.1\jbr\bin\.appmap\lib\java
java.nio.file.AccessDeniedException: C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.1.1\jbr\bin\.appmap
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:521)
	at java.base/java.nio.file.Files.createDirectory(Files.java:700)
	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:807)
	at java.base/java.nio.file.Files.createDirectories(Files.java:793)
	at appland.javaAgent.AppMapJavaAgentDownloadService.getOrCreateAgentDir(AppMapJavaAgentDownloadService.java:166)
	at appland.javaAgent.AppMapJavaAgentDownloadService.getJavaAgentPath(AppMapJavaAgentDownloadService.java:156)
	at appland.javaAgent.AppMapJavaAgentDownloadService.getJavaAgentPathIfExists(AppMapJavaAgentDownloadService.java:38)
	at appland.execution.AppMapJvmCommandLinePatcher.createJvmParams(AppMapJvmCommandLinePatcher.java:26)
	at appland.execution.AbstractAppMapJavaProgramPatcher.patchJavaParameters(AbstractAppMapJavaProgramPatcher.java:45)
	at com.intellij.execution.runners.JavaProgramPatcher.lambda$runCustomPatchers$0(JavaProgramPatcher.java:29)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:60)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:891)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:69)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:59)
	at com.intellij.execution.runners.JavaProgramPatcher.lambda$runCustomPatchers$1(JavaProgramPatcher.java:29)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.forEachExtensionSafe(ExtensionProcessingHelper.kt:32)
	at com.intellij.openapi.extensions.ExtensionPointName.forEachExtensionSafe(ExtensionPointName.kt:49)
	at com.intellij.execution.runners.JavaProgramPatcher.runCustomPatchers(JavaProgramPatcher.java:28)
	at appland.execution.AbstractAppMapJavaAgentRunner.patch(AbstractAppMapJavaAgentRunner.java:41)
	at com.intellij.execution.impl.DefaultJavaProgramRunner.patchJavaCommandLineParams(DefaultJavaProgramRunner.java:133)
	at com.intellij.execution.impl.DefaultJavaProgramRunner.lambda$doExecuteAsync$4(DefaultJavaProgramRunner.java:158)
	at com.intellij.execution.target.TargetEnvironmentAwareRunProfileState$1.run(TargetEnvironmentAwareRunProfileState.java:58)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by ahtrotta** [comment]
If I run IntelliJ as an Administrator then the Java agent jar is downloaded, but its in the wrong spot, as you can see from the above error. It gets stored in `C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.1.1\jbr\bin\.appmap\lib\java` instead of `C:\Users\ahtro\.appmap\lib\java`.
