### ISSUE TITLE
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "C:\Users\jonah.hawk\AppData\Local\JetBrains\appland-plugin\appmap\3.82.1\appmap-win-x64.exe" (in directory "C:\Users\jonah.hawk\Dropbox\Dev\Python\PyCharm\Midjourney"): CreateProcess error=1260, This program is blocked by group policy. For more information, contact your system administrator

### ISSUE THREAD

**Issue by jonahhawk** [getappmap/appmap-intellij-plugin#343]
Name | Value
----:|:-----
Plugin|appland.appmap
Version|0.44.0
IDE|PY-231.9161.41
OS|Windows 10.0
Last action|

### Stacktrace
```text
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "C:\Users\jonah.hawk\AppData\Local\JetBrains\appland-plugin\appmap\3.82.1\appmap-win-x64.exe" (in directory "C:\Users\jonah.hawk\Dropbox\Dev\Python\PyCharm\Midjourney"): CreateProcess error=1260, This program is blocked by group policy. For more information, contact your system administrator
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:356)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:84)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:44)
	at com.intellij.execution.process.KillableProcessHandler.<init>(KillableProcessHandler.java:41)
	at appland.cli.DefaultCommandLineService$2.<init>(DefaultCommandLineService.java:338)
	at appland.cli.DefaultCommandLineService.startProcess(DefaultCommandLineService.java:338)
	at appland.cli.DefaultCommandLineService.startProcesses(DefaultCommandLineService.java:282)
	at appland.cli.DefaultCommandLineService.start(DefaultCommandLineService.java:93)
	at appland.cli.RegisterContentRootsActivity.lambda$launchProcesses$0(RegisterContentRootsActivity.java:49)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:252)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException: Cannot run program "C:\Users\jonah.hawk\AppData\Local\JetBrains\appland-plugin\appmap\3.82.1\appmap-win-x64.exe" (in directory "C:\Users\jonah.hawk\Dropbox\Dev\Python\PyCharm\Midjourney"): CreateProcess error=1260, This program is blocked by group policy. For more information, contact your system administrator
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:432)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:346)
	... 18 more
Caused by: java.io.IOException: CreateProcess error=1260, This program is blocked by group policy. For more information, contact your system administrator
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:499)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:158)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 21 more

```

**Comment by jansorg** [comment]
`C:\Users\jonah.hawk\AppData\Local\JetBrains\appland-plugin\appmap\3.82.1\appmap-win-x64.exe` seems to be blocked by Windows machine's group policy. This is a binary bundled with the AppMap plugin to perform indexing and analysis of AppMap files.
