### ISSUE TITLE
The semantic release bot is not creating releases

### ISSUE THREAD

**Issue by ahtrotta** [getappmap/appmap-intellij-plugin#395]
The semantic release bot has not been automatically creating releases.

**Comment by jansorg** [comment]
@apotterri added the support, but I can look at it, too

**Comment by jansorg** [comment]
semantic-release is configured on Travis. It's currently printing this error, but I'm sure if that's the cause:

```
[7:17:58 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
2023-08-31T19:17:58.526Z semantic-release:get-git-auth-url Verifying ssh auth by attempting to push to  https://github.com/getappmap/appmap-intellij-plugin.git
2023-08-31T19:17:59.045Z semantic-release:git Error: Command failed with exit code 128: git push --dry-run --no-verify https://github.com/getappmap/appmap-intellij-plugin.git HEAD:main
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/getappmap/appmap-intellij-plugin.git/'
    at makeError (file:///home/travis/.nvm/versions/node/v18.17.1/lib/node_modules/semantic-release/node_modules/execa/lib/error.js:60:11)
    at handlePromise (file:///home/travis/.nvm/versions/node/v18.17.1/lib/node_modules/semantic-release/node_modules/execa/index.js:124:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async verifyAuth (file:///home/travis/.nvm/versions/node/v18.17.1/lib/node_modules/semantic-release/lib/git.js:209:5)
    at async default (file:///home/travis/.nvm/versions/node/v18.17.1/lib/node_modules/semantic-release/lib/get-git-auth-url.js:93:5)
    at async run (file:///home/travis/.nvm/versions/node/v18.17.1/lib/node_modules/semantic-release/index.js:67:27)
    at async Module.default (file:///home/travis/.nvm/versions/node/v18.17.1/lib/node_modules/semantic-release/index.js:275:22)
    at async default (file:///home/travis/.nvm/versions/node/v18.17.1/lib/node_modules/semantic-release/cli.js:55:5)
```

**Comment by jansorg** [comment]
The [Travis log](https://app.travis-ci.com/github/getappmap/appmap-intellij-plugin/jobs/608845285#L1094) ends with `[semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"`.
This seems incomplete to me.

https://github.com/semantic-release/release-notes-generator mentions:
> Note: For presets that expects a configuration object, such as [conventionalcommits](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-conventionalcommits), the presetConfig option must be set.

**Comment by dividedmind** [comment]
I believe the problem is GitHub authentication; GitHub token on Travis is probably expired. @dustinbyrne can you take a look?

**Comment by dustinbyrne** [comment]
The token for this repository is still valid

**Comment by dividedmind** [comment]
Seems to work now?
