### ISSUE TITLE
com.intellij.util.IncorrectOperationException error

### ISSUE THREAD

**Issue by jansorg** [getappmap/appmap-intellij-plugin#412]
Name | Value
----:|:-----
Plugin|appland.appmap
Version|0.48.0
IDE|IU-213.7172.25
OS|Windows 10 10.0
Last action|

### Stacktrace
```text
com.intellij.util.IncorrectOperationException: Sorry but parent: {DUMB_AWARE=true, FILE_KEY=file://C:/Users/jansorg/IdeaProjects/Java-WebSocket/target/appmap/junit/org_java_websocket_drafts_Draft_6455Test_testGetProtocol.appmap.json, notifications added to the editor=[]} (class appland.webviews.appMap.AppMapFileEditor) has already been disposed (see the cause for stacktrace) so the child: [] (class com.intellij.util.messages.impl.MessageBusConnectionImpl) will never be disposed
	at com.intellij.openapi.util.ObjectTree.register(ObjectTree.java:53)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:118)
	at com.intellij.util.messages.impl.MessageBusImpl.connect(MessageBusImpl.java:105)
	at com.intellij.util.messages.impl.CompositeMessageBus.connect(CompositeMessageBus.java:25)
	at appland.webviews.appMap.AppMapFileEditor.afterInit(AppMapFileEditor.java:138)
	at appland.webviews.appMap.AppMapFileEditor.afterInit(AppMapFileEditor.java:53)
	at appland.webviews.WebviewEditor$1.run(WebviewEditor.java:259)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:436)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:120)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:496)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by augustd** [comment]
This public error report includes information about the username (jansorg) on the host system: 
```
FILE_KEY=file://C:/Users/jansorg/IdeaProjects
```

**Comment by jansorg** [comment]
Thanks for noticing! This isn't too bad, as it's easy go guess anyway. But I'll take better care next time...
