### ISSUE TITLE
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'value' of com/intellij/util/io/IOUtil.writeUTF must not be null

### ISSUE THREAD

**Issue by Its-Arul** [getappmap/appmap-intellij-plugin#453]
Name | Value
----:|:-----
Plugin|appland.appmap
Version|0.48.0
IDE|PY-232.8660.197
OS|Windows 11.0
Last action|

### Stacktrace
```text
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'value' of com/intellij/util/io/IOUtil.writeUTF must not be null
	at com.intellij.util.io.IOUtil.$$$reportNull$$$0(IOUtil.java)
	at com.intellij.util.io.IOUtil.writeUTF(IOUtil.java)
	at appland.index.BasicAppMapMetadataExternalizer.save(BasicAppMapMetadataExternalizer.java:31)
	at appland.index.BasicAppMapMetadataExternalizer.save(BasicAppMapMetadataExternalizer.java:12)
	at com.intellij.util.indexing.impl.ValueContainerImpl.saveTo(ValueContainerImpl.java:442)
	at com.intellij.util.indexing.impl.ChangeTrackingValueContainer.saveTo(ChangeTrackingValueContainer.java:159)
	at com.intellij.util.indexing.impl.ValueContainerExternalizer.save(ValueContainerExternalizer.java:27)
	at com.intellij.util.indexing.impl.ValueContainerExternalizer.save(ValueContainerExternalizer.java:14)
	at com.intellij.util.io.PersistentMapImpl.doPut(PersistentMapImpl.java:436)
	at com.intellij.util.io.PersistentMapImpl.put(PersistentMapImpl.java:415)
	at com.intellij.util.indexing.impl.ValueContainerMap.merge(ValueContainerMap.java:60)
	at com.intellij.util.indexing.impl.MapIndexStorage.onDropFromCache(MapIndexStorage.java:94)
	at com.intellij.util.indexing.impl.MapIndexStorage.lambda$initMapAndCache$1(MapIndexStorage.java:75)
	at com.intellij.util.indexing.impl.MapIndexStorageSlruCache$cache$1.onDropFromCache(MapIndexStorageCache.kt:63)
	at com.intellij.util.indexing.impl.MapIndexStorageSlruCache$cache$1.onDropFromCache(MapIndexStorageCache.kt:57)
	at com.intellij.util.containers.SLRUMap.clear(SLRUMap.java:158)
	at com.intellij.util.indexing.impl.MapIndexStorageSlruCache.invalidateAll(MapIndexStorageCache.kt:81)
	at com.intellij.util.indexing.impl.MapIndexStorage.clearCachedMappings(MapIndexStorage.java:335)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapIndexStorage.processKeys(VfsAwareMapIndexStorage.java:104)
	at com.intellij.util.indexing.impl.storage.TransientChangesIndexStorage.processKeys(TransientChangesIndexStorage.java:144)
	at com.intellij.util.indexing.storage.MapReduceIndexBase.lambda$processAllKeys$0(MapReduceIndexBase.java:49)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:246)
	at com.intellij.util.indexing.storage.MapReduceIndexBase.processAllKeys(MapReduceIndexBase.java:48)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.processAllKeys(CompositeInvertedIndexBase.java:123)
	at com.intellij.util.indexing.FileBasedIndexEx.processAllKeys(FileBasedIndexEx.java:176)
	at com.intellij.util.indexing.FileBasedIndexImpl.processAllKeys(FileBasedIndexImpl.java:854)
	at appland.index.AppMapNameIndex.getAppMapMetadataDirectories(AppMapNameIndex.java:35)
	at appland.index.AppMapMetadataService.findAppMaps(AppMapMetadataService.java:60)
	at appland.index.AppMapMetadataService.findAppMaps(AppMapMetadataService.java:44)
	at appland.toolwindow.AppMapModel.lambda$calculateAppMaps$0(AppMapModel.java:81)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode$lambda$0(DumbService.kt:76)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode$lambda$2(DumbService.kt:117)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:923)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:76)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.kt:110)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.kt:76)
	at appland.toolwindow.AppMapModel.calculateAppMaps(AppMapModel.java:80)
	at appland.toolwindow.AppMapModel.getChildren(AppMapModel.java:72)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.getNode(AsyncTreeModel.java:568)
	at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:464)
	at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:430)
	at com.intellij.util.concurrency.Invoker$Task.run(Invoker.java:306)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:186)
	at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:165)
	at com.intellij.util.concurrency.Invoker$Background.lambda$offer$0(Invoker.java:433)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:24)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:249)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:227)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:215)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by Its-Arul** [comment]
Facing this error after installing AppMaps.
