### ISSUE TITLE
java.lang.Throwable: Slow operations are prohibited on EDT

### ISSUE THREAD

**Issue by jansorg** [getappmap/appmap-intellij-plugin#466]
This happened during my own testing.

Name | Value
----:|:-----
Plugin|appland.appmap
Version|0.49.0
IDE|IC-213.7172.25
OS|Linux 6.5.5-arch1-1
Last action|

### Stacktrace
```text
java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.util.SlowOperations.assertSlowOperationsAreAllowed(SlowOperations.java:102)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:784)
	at com.intellij.util.indexing.FileBasedIndexEx.processAllKeys(FileBasedIndexEx.java:134)
	at appland.index.AppMapNameIndex.getAppMapMetadataDirectories(AppMapNameIndex.java:35)
	at appland.index.AppMapMetadataService.findAppMaps(AppMapMetadataService.java:60)
	at appland.index.AppMapMetadataService.findAppMaps(AppMapMetadataService.java:44)
	at appland.toolwindow.appmap.nodes.RootNode.lambda$loadAppMaps$3(RootNode.java:89)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$0(DumbService.java:113)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:144)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:113)
	at appland.toolwindow.appmap.nodes.RootNode.loadAppMaps(RootNode.java:88)
	at appland.toolwindow.appmap.nodes.RootNode.getCachedAppMaps(RootNode.java:82)
	at appland.toolwindow.appmap.nodes.RootNode.getFiles(RootNode.java:63)
	at appland.toolwindow.appmap.AppMapWindowPanel.getDataImpl(AppMapWindowPanel.java:144)
	at appland.toolwindow.appmap.AppMapWindowPanel.getData(AppMapWindowPanel.java:114)
	at com.intellij.ide.impl.DataManagerImpl.getDataFromProvider(DataManagerImpl.java:71)
	at com.intellij.openapi.actionSystem.impl.PreCachedDataContext2.doPreGetAllData(PreCachedDataContext2.java:255)
	at com.intellij.openapi.actionSystem.impl.PreCachedDataContext2.preGetAllData(PreCachedDataContext2.java:229)
	at com.intellij.openapi.actionSystem.impl.PreCachedDataContext2.<init>(PreCachedDataContext2.java:96)
	at com.intellij.openapi.actionSystem.impl.Utils.newPreCachedDataContext(Utils.java:83)
	at com.intellij.openapi.actionSystem.impl.Utils.wrapToAsyncDataContext(Utils.java:71)
	at com.intellij.openapi.actionSystem.impl.Utils.wrapDataContext(Utils.java:89)
	at com.intellij.ide.navigationToolbar.NavBarModel.wrapDataContext(NavBarModel.java:116)
	at com.intellij.ide.navigationToolbar.NavBarModel.updateModelAsync(NavBarModel.java:104)
	at com.intellij.ide.navigationToolbar.NavBarUpdateQueue.requestModelUpdateFromContextOrObject(NavBarUpdateQueue.java:86)
	at com.intellij.ide.navigationToolbar.NavBarUpdateQueue$1.lambda$run$0(NavBarUpdateQueue.java:58)
	at org.jetbrains.concurrency.AsyncPromise$onSuccess$1.accept(AsyncPromise.kt:84)
	at org.jetbrains.concurrency.AsyncPromise$onSuccess$1.accept(AsyncPromise.kt:16)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251)
	at org.jetbrains.concurrency.AsyncPromise.onSuccess(AsyncPromise.kt:78)
	at org.jetbrains.concurrency.AsyncPromise.onSuccess(AsyncPromise.kt:16)
	at com.intellij.ide.navigationToolbar.NavBarUpdateQueue$1.run(NavBarUpdateQueue.java:57)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:333)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:323)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:273)
	at com.intellij.util.ui.EdtInvocationManager.invokeAndWaitIfNeeded(EdtInvocationManager.java:147)
	at com.intellij.util.ui.UIUtil.invokeAndWaitIfNeeded(UIUtil.java:2196)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:284)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:241)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:240)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:385)
	at com.intellij.util.Alarm$Request.run(Alarm.java:374)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by jansorg** [comment]
This should be fixed now because we're support slow data providers in the AppMap panel now.
