### ISSUE TITLE
java.lang.RuntimeException: com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corrupted C:\Users\Matrix\AppData\Local\JetBrains\PyCharmCE2022.3\caches\names.dat

### ISSUE THREAD

**Issue by ShubhamRecurssion** [getappmap/appmap-intellij-plugin#480]
Name | Value
----:|:-----
Plugin|appland.appmap
Version|0.42.1
IDE|PC-223.8617.48
OS|Windows 11 10.0
Last action|

### Stacktrace
```text
java.lang.RuntimeException: com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corrupted C:\Users\Matrix\AppData\Local\JetBrains\PyCharmCE2022.3\caches\names.dat
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:132)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSConnection.handleError(PersistentFSConnection.java:319)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.handleError(FSRecords.java:953)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.getNameId(FSRecords.java:682)
	at com.intellij.openapi.vfs.newvfs.persistent.InvertedNameIndex.processData(InvertedNameIndex.java:149)
	at com.intellij.openapi.vfs.newvfs.persistent.InvertedNameIndex.processFilesWithNames(InvertedNameIndex.java:49)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.processFilesWithNames(FSRecords.java:668)
	at com.intellij.util.indexing.FileBasedIndexScanUtil.processFilesContainingAnyKey(FileBasedIndexScanUtil.java:240)
	at com.intellij.util.indexing.FileBasedIndexImpl.processFilesContainingAnyKey(FileBasedIndexImpl.java:1146)
	at com.intellij.psi.search.FilenameIndex.getVirtualFilesByNames(FilenameIndex.java:225)
	at com.intellij.psi.search.FilenameIndex.getVirtualFilesByName(FilenameIndex.java:62)
	at com.intellij.psi.search.FilenameIndex.getVirtualFilesByName(FilenameIndex.java:78)
	at com.intellij.psi.search.FilenameIndex.getVirtualFilesByName(FilenameIndex.java:72)
	at appland.problemsView.FindingsManager.findFindingsFiles(FindingsManager.java:360)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor.callWrapped(NonBlockingReadActionImpl.java:746)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor$MonitoredComputation.call(NonBlockingReadActionImpl.java:778)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:573)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:537)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1111)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:71)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:128)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:109)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:68)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:68)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:106)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:71)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:537)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:444)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corrupted C:\Users\Matrix\AppData\Local\JetBrains\PyCharmCE2022.3\caches\names.dat
	at com.intellij.util.io.PersistentEnumeratorBase.catchCorruption(PersistentEnumeratorBase.java:628)
	at com.intellij.util.io.PersistentEnumeratorBase.doEnumerate(PersistentEnumeratorBase.java:272)
	at com.intellij.util.io.PersistentEnumeratorBase.enumerate(PersistentEnumeratorBase.java:285)
	at com.intellij.util.io.PersistentEnumerator.enumerate(PersistentEnumerator.java:125)
	at com.intellij.util.io.PersistentStringEnumerator.enumerate(PersistentStringEnumerator.java:70)
	at com.intellij.util.io.PersistentStringEnumerator.enumerate(PersistentStringEnumerator.java:24)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.getNameId(FSRecords.java:676)
	... 39 more

```

**Comment by brikelly** [comment]
Hi @ShubhamRecurssion , thank you for submitting this. Based on your stack trace, it looks like an internal PyCharm file, `names.dat`, is corrupt. Did your IDE recently crash, perhaps?

**Comment by jansorg** [comment]
The exception is thrown when an index, which is created by the IDE itself, is accessed (the index of filenames). The exception is most likely caused by broken indexes (e.g. due to a crash of the IDE), which are outside our control. 
More recent IDEs have `File > Cache Recovery`. At last ressort, `File > Invalidate Caches` helps to recreate all indexes.
