### ISSUE TITLE
Verify that uninstalling the plugin is possible, including shutdown of AppMap processes

### ISSUE THREAD

**Issue by jansorg** [getappmap/appmap-intellij-plugin#597]
A user reported that uninstalling and unloading the plugin wasn't terminating.
https://x.com/alexandreverri/status/1762894679434047990?s=46&t=1DqxEuCOk31Q5QmqySaUOA

**Comment by reedjones** [comment]
I have the same problem

**Comment by jansorg** [comment]
@reedjones Thanks for the details. This isn't supposed to happen, of course.
Which OS and JetBrains IDE are you using?

**Comment by jansorg** [comment]
Reproduced on Linux:
```
"AWT-EventQueue-0@3206" prio=6 tid=0x1e nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 waiting for ApplicationImpl pooled thread 10@21030 to release lock on <0xc796> (a appland.cli.DefaultCommandLineService)
	  at appland.cli.DefaultCommandLineService.stopAll(DefaultCommandLineService.java:174)
	  at appland.cli.DefaultCommandLineService.stopAll(DefaultCommandLineService.java:167)
	  at appland.cli.DefaultCommandLineService.dispose(DefaultCommandLineService.java:249)
	  at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:139)
	  at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:169)
	  at com.intellij.openapi.util.Disposer.dispose(Disposer.java:219)
	  at com.intellij.openapi.util.Disposer.dispose(Disposer.java:207)
	  at com.intellij.serviceContainer.ComponentManagerImpl.unloadServices(ComponentManagerImpl.kt:958)
	  at com.intellij.openapi.client.ClientAwareComponentManager.unloadServices(ClientAwareComponentManager.kt:72)
	  at com.intellij.ide.plugins.DynamicPlugins.unloadModuleDescriptorNotRecursively(DynamicPlugins.kt:735)
	  at com.intellij.ide.plugins.DynamicPlugins.access$unloadModuleDescriptorNotRecursively(DynamicPlugins.kt:95)
	  at com.intellij.ide.plugins.DynamicPlugins$unloadPlugin$2.run(DynamicPlugins.kt:487)
	  at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1015)
	  at com.intellij.ide.plugins.DynamicPlugins.unloadPlugin(DynamicPlugins.kt:473)
	  at com.intellij.ide.plugins.DynamicPlugins$unloadPluginWithProgress$2.run(DynamicPlugins.kt:395)
	  at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	  at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$1096.1063831697.run(Unknown Source:-1)
	  at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	  at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$407.985444746.compute(Unknown Source:-1)
	  at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	  at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	  at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	  at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	  at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	  at com.intellij.openapi.progress.util.PotemkinProgress.runInSwingThread(PotemkinProgress.java:164)
	  at com.intellij.ide.plugins.DynamicPlugins.unloadPluginWithProgress(DynamicPlugins.kt:394)
	  at com.intellij.ide.plugins.PluginInstaller.uninstallDynamicPlugin(PluginInstaller.java:107)
	  at com.intellij.ide.plugins.newui.MyPluginModel.apply(MyPluginModel.java:142)
	  at com.intellij.ide.plugins.PluginManagerConfigurable.apply(PluginManagerConfigurable.java:1765)
	  at com.intellij.openapi.options.ex.ConfigurableWrapper.apply(ConfigurableWrapper.java:179)
	  at com.intellij.openapi.options.newEditor.ConfigurableEditor.apply(ConfigurableEditor.java:324)
	  at com.intellij.openapi.options.newEditor.SettingsEditor$5.apply(SettingsEditor.java:207)
	  at com.intellij.openapi.options.newEditor.SettingsEditor.apply(SettingsEditor.java:429)
	  at com.intellij.openapi.options.newEditor.SettingsDialog.applyAndClose(SettingsDialog.java:198)
	  at com.intellij.openapi.options.newEditor.SettingsDialog.doOKAction(SettingsDialog.java:190)
	  at com.intellij.openapi.ui.DialogWrapper$OkAction.doAction(DialogWrapper.java:1853)
	  at com.intellij.openapi.ui.DialogWrapper$DialogWrapperAction.actionPerformed(DialogWrapper.java:1807)
	  at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	  at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	  at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	  at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	  at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:270)
	  at java.awt.Component.processMouseEvent(Component.java:6654)
	  at javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	  at java.awt.Component.processEvent(Component.java:6419)
	  at java.awt.Container.processEvent(Container.java:2263)
	  at java.awt.Component.dispatchEventImpl(Component.java:5029)
	  at java.awt.Container.dispatchEventImpl(Container.java:2321)
	  at java.awt.Component.dispatchEvent(Component.java:4861)
	  at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	  at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	  at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	  at java.awt.Container.dispatchEventImpl(Container.java:2307)
	  at java.awt.Window.dispatchEventImpl(Window.java:2793)
	  at java.awt.Component.dispatchEvent(Component.java:4861)
	  at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	  at java.awt.EventQueue$4.run(EventQueue.java:727)
	  at java.awt.EventQueue$4.run(EventQueue.java:721)
	  at java.security.AccessController.doPrivileged(AccessController.java:-1)
	  at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	  at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	  at java.awt.EventQueue$5.run(EventQueue.java:751)
	  at java.awt.EventQueue$5.run(EventQueue.java:749)
	  at java.security.AccessController.doPrivileged(AccessController.java:-1)
	  at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	  at java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	  at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	  at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:820)
	  at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:743)
	  at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	  at com.intellij.ide.IdeEventQueue$$Lambda$584.405354243.compute(Unknown Source:-1)
	  at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	  at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	  at com.intellij.ide.IdeEventQueue$$Lambda$582.1207958241.run(Unknown Source:-1)
	  at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	  at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	  at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	  at com.intellij.ide.IdeEventQueue$$Lambda$581.1653751976.run(Unknown Source:-1)
	  at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	  at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	  at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	  at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	  at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:121)
	  at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	  at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	  at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	  at java.security.AccessController.doPrivileged(AccessController.java:-1)
	  at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	  at java.awt.Dialog.show(Dialog.java:1070)
	  at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:702)
	  at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:439)
	  at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1668)
	  at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1626)
	  at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:90)
	  at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:50)
	  at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:37)
	  at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:65)
	  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:579)
	  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:704)
	  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$$Lambda$1538.1258299377.run(Unknown Source:-1)
	  at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	  at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
	  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$11(IdeKeyEventDispatcher.java:704)
	  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$$Lambda$1537.158805227.run(Unknown Source:-1)
	  at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:256)
	  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:701)
	  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:645)
	  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:590)
	  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:473)
	  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:462)
	  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:227)
	  at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:804)
	  at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:740)
	  at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	  at com.intellij.ide.IdeEventQueue$$Lambda$584.405354243.compute(Unknown Source:-1)
	  at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	  at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	  at com.intellij.ide.IdeEventQueue$$Lambda$582.1207958241.run(Unknown Source:-1)
	  at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:119)
	  at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	  at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	  at com.intellij.ide.IdeEventQueue$$Lambda$581.1653751976.run(Unknown Source:-1)
	  at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	  at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	  at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	  at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	  at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	  at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	  at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	  at java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

"ApplicationImpl pooled thread 10@21030" prio=4 tid=0x9b nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	 blocks AWT-EventQueue-0@3206
	 blocks ApplicationImpl pooled thread 27@43059
	  at com.intellij.openapi.project.DumbServiceImpl.waitForSmartMode(DumbServiceImpl.java:468)
	  at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:149)
	  at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:113)
	  at appland.cli.DefaultCommandLineService.doRefreshForOpenProjectsLocked(DefaultCommandLineService.java:359)
	  at appland.cli.DefaultCommandLineService.refreshForOpenProjects(DefaultCommandLineService.java:122)
	  - locked <0xc796> (a appland.cli.DefaultCommandLineService)
	  at appland.cli.DefaultCommandLineService$$Lambda$1870.371828621.run(Unknown Source:-1)
	  at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:295)
	  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	  at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	  at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	  at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	  at java.security.AccessController.doPrivileged(AccessController.java:-1)
	  at java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	  at java.lang.Thread.run(Thread.java:829)

```
