### ISSUE TITLE
java.lang.Throwable: unable to load AppMap file content: /workspace/meetid/api/tmp/appmap/requests/1712744454_573452_http_localhost_8001_teams.appmap.json

### ISSUE THREAD

**Issue by phuong-mid** [getappmap/appmap-intellij-plugin#654]
Name | Value
----:|:-----
Plugin|appland.appmap
Version|0.63.0
IDE|PY-233.13763.11
OS|Linux 6.5.0-26-generic
Last action|

### Stacktrace
```text
java.lang.Throwable: unable to load AppMap file content: /workspace/meetid/api/tmp/appmap/requests/1712744454_573452_http_localhost_8001_teams.appmap.json
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at appland.files.AppMapFiles.lambda$loadFileContent$0(AppMapFiles.java:221)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:909)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:65)
	at appland.files.AppMapFiles.loadFileContent(AppMapFiles.java:213)
	at appland.files.AppMapFiles.loadAppMapFile(AppMapFiles.java:314)
	at appland.files.AppMapFiles.loadAppMapFile(AppMapFiles.java:240)
	at appland.webviews.appMap.AppMapFileEditor.createInitData(AppMapFileEditor.java:63)
	at appland.webviews.appMap.AppMapFileEditor.createInitData(AppMapFileEditor.java:39)
	at appland.webviews.WebviewEditor$1.run(WebviewEditor.java:239)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:132)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:484)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:248)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:248)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:498)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

**Comment by jansorg** [comment]
The latest release provides more context in the debug message. Please reopen when this happens again with the latest release. Thanks!
